---
# virtualbox_user:
virtualbox_os_distribution: "{{ global_os_distribution | default(ansible_distribution) }}"
virtualbox_rpm_repository: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
virtualbox_version: 5.1
virtualbox_license_acceptance_key: 715c7246dc0f779ceab39446812362b2f9bf64a55ed5d3a905f053cfab36da9e
