---
- name: install x62
  hosts: x62
  roles:
    - role: base
      tags:
        - base

    - role: kernel.devel
      tags:
        - kernel

    - role: selinux.config
      tags:
        - selinux

    - role: selinux.policies
      tags: selinux

    - role: rpmfusion
      when: "ansible_distribution | lower == 'fedora'"
      tags:
        - rpmfusion

    - role: tlp
      tags:
        - tlp

    - role: virtualbox
      tags:
        - virtualbox

    - role: sublime_text
      tags:
        - sublime

    - role: rvm_io.ruby
      rvm1_rubies: "{{ ruby_install_versions }}"
      rvm1_install_flags: --auto-dotfiles --user-install
      rvm1_ruby_install_flags: --with-jemalloc
      rvm1_install_path: "/home/{{ global_target_user }}/.rvm"
      rvm1_user: "{{ global_target_user }}"
      become: true
      tags:
        - ruby

    - role: vagrant
      tags:
        - vagrant

    - role: adobe_flash
      tags:
        - flash

    - role: nuvola_player
      tags:
        - nuvola

    - role: dotfiles
      tags:
        - dotfiles

    - role: z
      tags:
        - z

    - role: ulauncher
      tags:
        - ulauncher

    - role: fubarhouse.nodejs
      node_version: 6.11.3
      node_versions:
        - 4.8.4
        - 7.10.1
        - 8.4.0
      node_packages:
        - yarn
      install_nvm: true
      install_nvm_git: true
      install_nodejs: true
      install_npm: true
      tags:
        - nodejs

    - role: pip.packages
      tags:
        - python

    - role: pidgin
      tags:
        - pidgin

    - role: dbeaver
      tags:
        - dbeaver

    - role: calibre
      tags:
        - calibre
