---
- name: install
  hosts: all
  roles:
    - role: base
      tags:
        - base

    - role: kernel.devel
      tags:
        - kernel

    - role: selinux.config
      tags:
        - selinux

    - role: selinux.policies
      tags: selinux

    - role: rpmfusion
      when: "ansible_distribution | lower == 'fedora'"
      tags:
        - rpmfusion

    - role: tlp
      tags:
        - tlp

    - role: virtualbox
      tags:
        - virtualbox

    - role: sublime_text
      tags:
        - sublime

    - role: rvm_io.ruby
      rvm1_rubies: "{{ ruby_install_versions }}"
      rvm1_install_flags: --auto-dotfiles --user-install
      rvm1_ruby_install_flags: --with-jemalloc
      rvm1_install_path: "/home/{{ lookup('env', 'USER') }}/.rvm"
      rvm1_user: "{{ lookup('env', 'USER') }}"
      become: true
      tags:
        - ruby

    - role: vagrant
      tags:
        - vagrant

    - role: adobe_flash
      tags:
        - flash

    - role: nuvola_player
      tags:
        - nuvola

    - role: dotfiles
      tags:
        - dotfiles
