---
- name: install
  hosts: all
  roles:
    - role: base
      tags:
        - base

    - role: kernel.devel
      tags:
        - kernel

    - role: selinux.config
      tags:
        - selinux

    - role: selinux.policies
      tags: selinux

    - role: rpmfusion
      when: "ansible_distribution | lower == 'fedora'"
      tags:
        - rpmfusion

    - role: tlp
      tags:
        - tlp

    - role: virtualbox
      tags:
        - virtualbox

    - role: sublime_text
      tags:
        - sublime
