---
- name: install packages
  pip:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - setuptools
    - virtualenv

- name: install user packages
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: --user
  with_items:
    - mysqlclient
    - psycopg2
    - awscli
    - httplib2
    - cryptography
    - boto3
    - certifi
    - flatdict
    - prettytable
    - s3cmd
    - ansible
    - jq
