---
- name: check vars
  fail:
    msg: "variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - dotfiles_user
    - dotfiles_home_path
    - dotfiles_group

- name: create bash lib dir
  file:
    path: "{{ dotfiles_home_path }}/.bash_lib"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rwx,g=rwx,o=rx

- name: create code dir
  file:
    path: "{{ dotfiles_home_path }}/code"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rwx,g=rwx,o=rx

- name: create src dir
  file:
    path: "{{ dotfiles_home_path }}/code/src"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rwx,g=rwx,o=rx

- name: create packages dir
  file:
    path: "{{ dotfiles_home_path }}/code/src/packages"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rwx,g=rwx,o=rx

- name: create backup dir
  file:
    path: "{{ dotfiles_home_path }}/code/backup"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rwx,g=rwx,o=rx

- name: create user config dir
  file:
    path: "{{ dotfiles_home_path }}/.config"
    state: directory
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rwx,g=rwx,o=rx

- import_tasks: "distributions/{{ dotfiles_os_distribution | lower }}.yml"

- name: add home specific rc files
  template:
    src: "home/{{ item }}.j2"
    dest: "{{ dotfiles_home_path }}/.{{ item }}"
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rw,g=rw,o=r
  with_items:
    - irbrc
    - gitconfig
    - inputrc
