---
- name: check if calibre is installed
  stat:
    path: /opt/calibre
  register: calibre_install_result

- name: install calibre
  shell: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  args:
    chdir: /tmp
  become: true
  when: not calibre_install_result.stat.exists
