---
- name: check kupfer plugin exists
  stat:
    path: /usr/share/kupfer/kupfer/plugin/applications.py
  register: kupfer_application_plugin_result

- name: check kupfer version
  shell: awk -F "=" '/^VERSION/ {gsub(/[ \t]/, "", $2); print $2}' version_subst.py | tr -d '"'
  args:
    chdir: /usr/share/kupfer/kupfer
  register: kupfer_version_result
  when: kupfer_application_plugin_result.stat.exists

- name: patch kupfer application plugin to support cinnamon
  copy:
    src: usr/share/kupfer/kupfer/plugin/applications.py
    dest: /usr/share/kupfer/kupfer/plugin/applications.py
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: true
  become: true
  when: "kupfer_application_plugin_result.stat.exists and kupfer_version_result.stdout == 'v208'"
