---
vagrant_os_distribution: "{{ global_os_distribution | default(ansible_distribution) }}"
vagrant_version: "1.9.7"
vagrant_platform: x86_64
vagrant_rpm_url: "https://releases.hashicorp.com/vagrant/{{ vagrant_version }}/vagrant_{{ vagrant_version }}_{{ vagrant_platform }}.rpm"
