---
- name: git clone repo
  git:
    repo: "{{ z_git_repo }}"
    dest: "{{ z_src_path }}"
    version: "{{ z_git_version }}"

- name: link z to bash lib
  file:
    src: "{{ z_src_path }}/z.sh"
    dest: "{{ lookup('env', 'HOME') }}/.bash_lib/z.sh"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    state: link
