---
- name: update packages
  package:
    name: "*"
    state: latest
  become: true

- include_tasks: "distributions/{{ base_os_distribution | lower }}.yml"

- name: remove thunderbird
  dnf:
    name: thunderbird
    state: absent
  become: true
