---
# FIXME: dnf group installs are broken
# https://bugzilla.redhat.com/show_bug.cgi?id=1471017
#
# - name: install development packages
#   dnf:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - "@Development tools"
#     - "@Virtualization"
#   become_user: true

- name: install development tools
  command: "dnf install '@{{ item }}' -y"
  with_items:
    - Development tools
    - Virtualization
  register: base_install_development_tools_result
  changed_when: "(base_install_development_tools_result.rc == 0) and ('is already installed' not in base_install_development_tools_result.stderr)"
  become: true

- name: install packages
  dnf:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - curl
    - libcurl
    - libcurl-devel
    - jemalloc
    - jemalloc-devel
    - vim
    - speedcrunch
    - mariadb
    - mariadb-devel
    - postgresql
    - postgresql-devel
    - mongo-tools
    - make
    - autoconf
    - tig
    - htop
    - gmp-devel
    - python-gpgme
    - i2c-tools
    - nfs-utils
    - libnfsidmap
    - lm_sensors
    - monitor-edid
    - tree
    - xournal
    - unclutter
    - gparted
    - p7zip
    - p7zip-plugins
    - unar
    - openssl
    - openssl-devel
    - readline
    - readline-devel
    - zlib-devel
    - libffi-devel
    - ncurses-devel
    - libyaml-devel
    - libxml2
    - libxml2-devel
    - libxslt-devel
    - libsqlite3x-devel
    - autossh
    - libselinux-python
    - screenfetch
    - automake
    - libtool
    - bison
    - bzip2
    - gdbm-devel
    - ruby
    - vim-X11
    - colordiff
    - jq
    - redshift
    - redshift-gtk
    - powertop
    - python-devel
    - wireshark-qt
    - nemo-dropbox
    - intel-gpu-tools
    - backintime-qt4
    - redis
    - screen
    - tmux
    - tmate
    - dnf-plugins-core
    - dnf-plugin-system-upgrade
    - mediawriter
    - geteltorito
  become: true

- name: remove thunderbird
  dnf:
    name: thunderbird
    state: absent
  become: true
