---
- name: add .dotrc
  template:
    src: fedora/dotrc.j2
    dest: "{{ dotfiles_home_path }}/.dotrc"
    mode: u=rw,g=rw,o=r
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"

- name: add dotrc to bash_profile
  lineinfile:
    path: "{{ dotfiles_home_path }}/.bash_profile"
    line: '[[ -f "$HOME/.dotrc" ]] && source $HOME/.dotrc'
    insertafter: fi

- name: add fedora rc files
  template:
    src: "fedora/{{ item }}.j2"
    dest: "{{ dotfiles_home_path }}/.{{ item }}"
    owner: "{{ dotfiles_user }}"
    group: "{{ dotfiles_group }}"
    mode: u=rw,g=rw,o=r
  with_items:
    - vimrc
